export const ADD_NOTE = 'ADD_NOTE'
export const SET_NOTES = 'SET_NOTES'
export const SET_TOKEN = 'SET_TOKEN'
export const CLEAR_SESSION = 'CLEAR_SESSION'
export const CHANGE_USER = 'CHANGE_USER'
export const SET_NAME = 'SET_NAME'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_EMAIL = 'SET_EMAIL'